# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8624caf5655eea0e343f30b8658eb97fb1ce263d1a27b1dba4017e4e9222091ae4a6af6adb8a49aa4e7ea6b9fcd5a23f8e88b81a8ff0d255bae1f763d3b26de

test:
  secret_key_base: d6a83779659323ee01f43e887b9f54f87686852ae705752662d36cc3b490a79739cfcd57b18732c445e93ce6fa461d1d518802acb3215f8f8b45724614e882a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
